- clean: [ "~/.config/fisherman", "~/.config/fish" ]

- defaults:
    link:
      force: true
      create: true
      relink: true

- link:
   ~/.config/fish/alias.fish: fish/alias.fish
   ~/.config/fish/paths.fish: fish/paths.fish
   ~/.config/fish/config.fish: fish/config.fish
   ~/.config/fish/autoenv.fish: fish/autoenv.fish
   ~/.config/fish/functions/fisher.fish: fish/fisherman/fisher.fish
   ~/.config/fish/functions/tabcolor.fish: fish/tabcolor.fish
   ~/.config/fish/functions/ch.fish: fish/ch.fish
   ~/.config/fish/fishfile: fish/fishfile

- shell:
   - ["fish -c 'fisher; and fisher up'", "Install and update fisher plugins"]
