- shell:
   - ["defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string \"~/.dotfiles/iterm2\"", "Specifying iTerm preferences directory"]
   - ["defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true", "Configuring iTerm to use custom preferences directory"]
