- link:
   ~/.vscodestyles.css: vscode/vscodestyles.css
   ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json
   ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
