- clean: [ "~", "~/.config"]

- defaults:
    link:
      create: true
      relink: true
      
    shell:
      stdout: true

- shell:
  - ["git submodule update --init --recursive", "Installing submodules"]
